export const cities = [
  'Rio Branco - AC',
  'Maceió - AL',
  'Macapá - AP',
  'Manaus - AM',
  'Salvador - BA',
  'Fortaleza - CE',
  'Distrito Federal - DF',
  'Vitória - ES',
  'Goiânia - GO',
  'São Luís - MA',
  'Cuiabá - MT',
  'Campo Grande - MS',
  'Belo Horizonte - MG',
  'Belém - PA',
  'João Pessoa - PB',
  'Curitiba - PR',
  'Recife - PE',
  'Teresina - PI',
  'Rio de Janeiro - RJ',
  'Natal - RN',
  'Porta Alegre - RS',
  'Porto Velho - RO',
  'Boa Vista - RR',
  'Florianópolis - SC',
  'São Paulo - SP',
  'Aracaju - SE',
  'Palmas - TO',
];
